CREATE TABLE IF NOT EXISTS prayer_requests (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(80) NOT NULL,
  age TINYINT UNSIGNED NOT NULL,
  team VARCHAR(80) NOT NULL,
  request_text TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_prayer_requests_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS teams (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(80) NOT NULL,
  saint VARCHAR(120) NOT NULL,
  description TEXT NOT NULL,
  virtue VARCHAR(80) NOT NULL,
  motto VARCHAR(120) NOT NULL,
  image_url VARCHAR(600) NULL,
  primary_color CHAR(7) NOT NULL DEFAULT '#3f7c69',
  secondary_color CHAR(7) NOT NULL DEFAULT '#c99633',
  sort_order INT UNSIGNED NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_teams_active_order (is_active, sort_order, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
